import type { Team, Event, RankingRow, MediaItem, TeamRosterPlayer } from './types'

export const mockTeams: Team[] = [
  {
    id: 'ed3e6f8d-3176-4c15-a20f-0ccfe04a99ca', // Real Bodega Cats team ID
    name: 'Bodega Cats',
    logo_url: '/teams/bodega-cats-logo.png',
    created_at: '2023-01-15T00:00:00Z',
    current_rp: 1250,
    elo_rating: 1850,
    global_rank: 15,
    leaderboard_tier: 'Elite',
    money_won: 5000,
    player_rank_score: 85.5,
  },
  {
    id: '2',
    name: 'Capitol City Cats',
    logo_url: '/teams/capitol-city-cats-logo.webp',
    created_at: '2023-02-15T00:00:00Z',
    current_rp: 980,
    elo_rating: 1720,
    global_rank: 42,
    leaderboard_tier: 'Pro',
    money_won: 2500,
    player_rank_score: 72.3,
  },
]

export const mockTeamRoster: TeamRosterPlayer[] = [
  // Bodega Cats Roster
  {
    player_id: '1',
    team_id: 'ed3e6f8d-3176-4c15-a20f-0ccfe04a99ca', // Real Bodega Cats team ID
    team_name: 'Bodega Cats',
    gamertag: 'ShadowPaw',
    position: 'Point Guard',
    salary_tier: 'S',
    monthly_value: 5000,
    is_captain: true,
    is_player_coach: false,
    joined_at: '2023-01-15T00:00:00Z',
  },
  {
    player_id: '2',
    team_id: 'ed3e6f8d-3176-4c15-a20f-0ccfe04a99ca', // Real Bodega Cats team ID
    team_name: 'Bodega Cats',
    gamertag: 'MidnightMeow',
    position: 'Shooting Guard',
    salary_tier: 'A',
    monthly_value: 3500,
    is_captain: false,
    is_player_coach: false,
    joined_at: '2023-01-20T00:00:00Z',
  },
  {
    player_id: '3',
    team_id: 'ed3e6f8d-3176-4c15-a20f-0ccfe04a99ca', // Real Bodega Cats team ID
    team_name: 'Bodega Cats',
    gamertag: 'WhiskerShot',
    position: 'Lock',
    salary_tier: 'A',
    monthly_value: 3800,
    is_captain: false,
    is_player_coach: false,
    joined_at: '2023-01-25T00:00:00Z',
  },
  // Capitol City Cats Roster
  {
    player_id: '4',
    team_id: '2',
    team_name: 'Capitol City Cats',
    gamertag: 'SenatorPaws',
    position: 'Power Forward',
    salary_tier: 'A',
    monthly_value: 3200,
    is_captain: true,
    is_player_coach: false,
    joined_at: '2023-02-15T00:00:00Z',
  },
  {
    player_id: '5',
    team_id: '2',
    team_name: 'Capitol City Cats',
    gamertag: 'DiplomatKitty',
    position: 'Center',
    salary_tier: 'B',
    monthly_value: 2800,
    is_captain: false,
    is_player_coach: false,
    joined_at: '2023-02-20T00:00:00Z',
  },
  {
    player_id: '6',
    team_id: '2',
    team_name: 'Capitol City Cats',
    gamertag: 'AmbassadorClaw',
    position: 'Shooting Guard',
    salary_tier: 'B',
    monthly_value: 2600,
    is_captain: false,
    is_player_coach: false,
    joined_at: '2023-02-25T00:00:00Z',
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Spring Championship 2024',
    description: 'The biggest tournament of the spring season featuring top teams from across the league.',
    date: '2024-03-15',
    image: '/events/spring-championship.jpg',
    url: '/tournaments/spring-championship-2024',
    featured: true,
  },
  {
    id: '2',
    title: 'Pro-Am Showdown',
    description: 'A showcase event highlighting the best Pro-Am talent in the community.',
    date: '2024-04-20',
    image: '/events/pro-am-showdown.jpg',
    url: '/tournaments/pro-am-showdown',
    featured: false,
  },
  {
    id: '3',
    title: 'Summer League Finals',
    description: 'The culmination of the summer league season with championship glory on the line.',
    date: '2024-06-10',
    image: '/events/summer-league-finals.jpg',
    url: '/tournaments/summer-league-finals',
    featured: true,
  },
]

export const mockRankings: RankingRow[] = [
  {
    id: '1',
    rank: 1,
    player: 'ShadowPaw',
    team: 'Bodega Cats',
    points: 1250,
    wins: 45,
    losses: 15,
    winRate: 75.0,
  },
  {
    id: '2',
    rank: 2,
    player: 'WhiskerShot',
    team: 'Bodega Cats',
    points: 1180,
    wins: 42,
    losses: 18,
    winRate: 70.0,
  },
  {
    id: '3',
    rank: 3,
    player: 'SenatorPaws',
    team: 'Capitol City Cats',
    points: 1120,
    wins: 38,
    losses: 22,
    winRate: 63.3,
  },
  {
    id: '4',
    rank: 4,
    player: 'MidnightMeow',
    team: 'Bodega Cats',
    points: 1080,
    wins: 40,
    losses: 20,
    winRate: 66.7,
  },
  {
    id: '5',
    rank: 5,
    player: 'DiplomatKitty',
    team: 'Capitol City Cats',
    points: 1020,
    wins: 35,
    losses: 25,
    winRate: 58.3,
  },
]

export const mockMedia: MediaItem[] = [
  {
    id: '1',
    title: 'Bodega Cats vs Capitol City Cats - Championship Game',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=example1',
    thumbnail: '/media/championship-game-thumb.jpg',
    platform: 'youtube',
    date: '2024-01-15',
  },
  {
    id: '2',
    title: 'ShadowPaw 40-Point Performance',
    type: 'video',
    url: 'https://www.twitch.tv/videos/example2',
    thumbnail: '/media/shadowpaw-40pt-thumb.jpg',
    platform: 'twitch',
    date: '2024-01-10',
  },
  {
    id: '3',
    title: 'Team Practice Session Highlights',
    type: 'image',
    url: '/media/practice-highlights.jpg',
    thumbnail: '/media/practice-highlights-thumb.jpg',
    date: '2024-01-05',
  },
]
