import type { Team, Event, RankingRow, MediaItem } from './types'

export const mockTeams: Team[] = [
  {
    id: '1',
    name: 'Bodega Cats',
    tag: 'BCGC',
    description: 'The original crew from the streets, bringing that authentic bodega energy to competitive NBA 2K Pro-Am gaming.',
    logo_url: '/teams/bodega-cats-logo.png',
    region_id: 'us-east',
    is_active: true,
    created_at: '2023-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    created_by: 'user-1',
    players: [
      {
        id: '1',
        name: 'ShadowPaw',
        role: 'Captain',
        avatar_url: '/players/shadowpaw.jpg',
        current_team_id: '1',
        socials: {
          twitter: 'https://twitter.com/shadowpaw',
          twitch: 'https://twitch.tv/shadowpaw',
        },
      },
      {
        id: '2',
        name: 'MidnightMeow',
        role: 'Support',
        avatar_url: '/players/midnightmeow.jpg',
        current_team_id: '1',
        socials: {
          twitter: 'https://twitter.com/midnightmeow',
          youtube: 'https://youtube.com/@midnightmeow',
        },
      },
      {
        id: '3',
        name: 'WhiskerShot',
        role: 'DPS',
        avatar_url: '/players/whiskershot.jpg',
        current_team_id: '1',
        socials: {
          twitch: 'https://twitch.tv/whiskershot',
        },
      },
    ],
  },
  {
    id: '2',
    name: 'Capitol City Cats',
    tag: 'CCC',
    description: 'The sophisticated squad from the capital, combining strategic thinking with elite NBA 2K Pro-Am skills.',
    logo_url: '/teams/capitol-city-cats-logo.webp',
    region_id: 'us-east',
    is_active: true,
    created_at: '2023-02-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    created_by: 'user-2',
    players: [
      {
        id: '4',
        name: 'SenatorPaws',
        role: 'Captain',
        avatar_url: '/players/senatorpaws.jpg',
        current_team_id: '2',
        socials: {
          twitter: 'https://twitter.com/senatorpaws',
          twitch: 'https://twitch.tv/senatorpaws',
        },
      },
      {
        id: '5',
        name: 'DiplomatKitty',
        role: 'Tank',
        avatar_url: '/players/diplomatkitty.jpg',
        current_team_id: '2',
        socials: {
          twitter: 'https://twitter.com/diplomatkitty',
          youtube: 'https://youtube.com/@diplomatkitty',
        },
      },
      {
        id: '6',
        name: 'AmbassadorClaw',
        role: 'Flex',
        avatar_url: '/players/ambassadorclaw.jpg',
        current_team_id: '2',
        socials: {
          twitch: 'https://twitch.tv/ambassadorclaw',
        },
      },
    ],
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: '2K26 Tournament Series',
    description: 'A yearlong competitive ecosystem with $52,000 prize pool, running from October through August',
    date: '2025-10-01',
    image: '/events/2k26-series.jpg',
    url: '/events/2k26-series',
    featured: true,
  },
  {
    id: '2',
    title: 'Road to $25K Series',
    description: 'Our long-running league series that evolved into the UPA Summer Championships',
    date: '2025-06-15',
    image: '/events/road-to-25k.jpg',
    featured: true,
  },
  {
    id: '3',
    title: 'March Madness Tournament',
    description: 'Special themed bracket as part of the 2K26 Tournament Series',
    date: '2026-03-01',
    image: '/events/march-madness.jpg',
  },
]

export const mockRankings: RankingRow[] = [
  {
    id: '1',
    rank: 1,
    player: 'ShadowPaw',
    team: 'Bodega Cats',
    points: 2850,
    wins: 45,
    losses: 12,
    winRate: 78.9,
  },
  {
    id: '2',
    rank: 2,
    player: 'SenatorPaws',
    team: 'Capitol City Cats',
    points: 2780,
    wins: 42,
    losses: 15,
    winRate: 73.7,
  },
  {
    id: '3',
    rank: 3,
    player: 'MidnightMeow',
    team: 'Bodega Cats',
    points: 2650,
    wins: 38,
    losses: 18,
    winRate: 67.9,
  },
  {
    id: '4',
    rank: 4,
    player: 'DiplomatKitty',
    team: 'Capitol City Cats',
    points: 2520,
    wins: 35,
    losses: 20,
    winRate: 63.6,
  },
  {
    id: '5',
    rank: 5,
    player: 'WhiskerShot',
    team: 'Bodega Cats',
    points: 2400,
    wins: 32,
    losses: 22,
    winRate: 59.3,
  },
]

export const mockMedia: MediaItem[] = [
  {
    id: '1',
    title: 'Bodega Cats vs Capitol City Cats - Championship Match',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: '/media/championship-match.jpg',
    platform: 'youtube',
    date: '2024-01-15',
  },
  {
    id: '2',
    title: 'Behind the Scenes: Team Practice',
    type: 'video',
    url: 'https://www.twitch.tv/videos/123456789',
    thumbnail: '/media/team-practice.jpg',
    platform: 'twitch',
    date: '2024-01-10',
  },
  {
    id: '3',
    title: 'Tournament Highlights',
    type: 'image',
    url: '/media/tournament-highlights.jpg',
    thumbnail: '/media/tournament-highlights-thumb.jpg',
    date: '2024-01-05',
  },
]
